config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "reservations#new"

  get "/reservations", to: "reservations#index"
  get "/reservations/new", to: "reservations#new", as: "new_reservation"
  post "/reservations", to: "reservations#create"
  get "/search/new", to: "reservations#new_search", as: "new_search"
  get "/search", to: "reservations#search"
  get "/custom", to: "reservations#custom"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :num_billet, presence: true, uniqueness: true
  validates :price, numericality: true
  validates :age, numericality: { allow_nil: true }
  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid adress" }
  normalizes :email, with: -> email { email.downcase.gsub(/\s+/, "") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/import.rb
module Import
  class CsvImport
    require "csv"

    def call(params)
      col = { num_billet: "Numero billet", num_reserv: "Reservation", date: "Date reservation", hour: "Heure reservation", show_key: "Cle spectacle", show: "Spectacle", represent_key: "Cle representation", represent: "Representation", represent_date: "Date representation", represent_hour: "Heure representation", represent_end_date: "Date fin representation", represent_end_hour: "Heure fin representation", price: "Prix", product_type: "Type de produit", sales_channel: "Filiere de vente", lastname: "Nom", firstname: "Prenom", email: "Email", adress: "Adresse", pcode: "Code postal", country: "Pays", age: "Age", gender: "Sexe" }
      if params.is_a? ActionController::Parameters
        col = params
        f = File.open(params[:file])
      else
        f = File.open(params)
      end
      CSV.foreach(f, headers: true, col_sep: ";") do |row|
        reservation_params = {}
        reservation_params[:num_billet] = row[col[:num_billet]]
        reservation_params[:num_reserv] = row[col[:num_reserv]]
        reservation_params[:date] = convert(row[col[:date]])
        reservation_params[:hour] = row[col[:hour]]
        reservation_params[:show_key] = row[col[:show_key]]
        reservation_params[:show] = row[col[:show]]
        reservation_params[:represent_key] = row[col[:represent_key]]
        reservation_params[:represent] = row[col[:represent]]
        reservation_params[:represent_date] = convert(row[col[:represent_date]])
        reservation_params[:represent_hour] = row[col[:represent_hour]]
        reservation_params[:represent_end_date] = convert(row[col[:represent_end_date]])
        reservation_params[:represent_end_hour] = row[col[:represent_end_hour]]
        reservation_params[:price] = row[col[:price]]
        reservation_params[:product_type] = row[col[:product_type]]
        reservation_params[:sales_channel] = row[col[:sales_channel]]
        reservation_params[:lastname] = row[col[:lastname]]
        reservation_params[:firstname] = row[col[:firstname]]
        reservation_params[:email] = row[col[:email]]
        reservation_params[:adress] = row[col[:adress]]
        reservation_params[:pcode] = row[col[:pcode]]
        reservation_params[:country] = row[col[:country]]
        reservation_params[:age] = row[col[:age]]
        reservation_params[:gender] = row[col[:gender]]

        Reservation.create(reservation_params)
      end
    end

    private

    def convert(d)
      return nil if d.nil?
      Date.strptime(d, "%d/%m/%y")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include Import
  def index
    @reservations = Reservation.all
  end

  def new_search
  end

  def search
    return redirect_to reservations_url, notice: "Aucun résultat." if params[:query].blank?
    @reservations = Reservation.where("show LIKE ?", "%"+ params[:query] +"%")
    if @reservations.any?
      respond_to do |format|
        format.turbo_stream
        format.html
      end
    else
      redirect_to reservations_url, notice: "Aucun résultat."
    end
  end

  def new
  end

  def create
    if params[:reservation]
      check(params[:reservation][:file]); return if performed?
      CsvImport.new.call(reservation_params)
    else
      check(params[:file]); return if performed?
      CsvImport.new.call(params[:file])
    end
    redirect_to new_reservation_url, notice: "Données importées."
  end

  def custom
    @reservation = Reservation.new
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def check(file)
    return redirect_to new_reservation_url, alert: "Aucun fichier." if file.nil?
    return redirect_to new_reservation_url, alert: "Seulement les fichiers CSV sont autorisés." unless file.content_type == "text/csv"
  end

  def reservation_params
    params.require(:reservation).permit(:file, :num_billet, :num_reserv, :date, :hour, :show_key, :show, :represent_key, :represent, :represent_date, :represent_hour, :represent_end_date, :represent_end_hour, :price, :product_type, :sales_channel, :lastname, :firstname, :email, :adress, :pcode, :country, :age, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arena</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="navbar" class="mb-1">
      <% if notice %>
        <div id="notice" class="toast toast-success"><button class="btn btn-clear float-right" onclick="rmflash(this)"></button><%= notice %></div>
      <% end %>
      <% if alert %>
        <div id="alert" class="toast toast-error"><button class="btn btn-clear float-right" onclick="rmflash(this)"></button><%= alert %></div>
      <% end %>
    </div>
    <%= yield %>
    <script>function rmflash(x){x.parentElement.remove()}</script>
  </body>
</html>

app/views/reservations/_custom.html.erb
<%= form_with model: reservation, url: reservations_path do |form| %>
  <%= form.label "Fichier CSV" %>
  <%= form.file_field :file, accept: ".csv", class: "form-input" %>
  <%= form.label :num_billet, "Numero billet", class: "form-label" %>
  <%= form.text_field :num_billet, class: "form-input" %>
  <%= form.label :num_reserv, "Réservation", class: "form-label" %>
  <%= form.text_field :num_reserv, class: "form-input" %>
  <%= form.label :date, class: "form-label" %>
  <%= form.text_field :date, class: "form-input" %>
  <%= form.label :hour, "Heure", class: "form-label" %>
  <%= form.text_field :hour, class: "form-input" %>
  <%= form.label :show_key, "Clé spectacle", class: "form-label" %>
  <%= form.text_field :show_key, class: "form-input" %>
  <%= form.label :show, "Spectacle", class: "form-label" %>
  <%= form.text_field :show, class: "form-input" %>
  <%= form.label :represent_key, "Clé représentation", class: "form-label" %>
  <%= form.text_field :represent_key, class: "form-input" %>
  <%= form.label :represent, "Représentation", class: "form-label" %>
  <%= form.text_field :represent, class: "form-input" %>
  <%= form.label :represent_date, "Date représentation", class: "form-label" %>
  <%= form.text_field :represent_date, class: "form-input" %>
  <%= form.label :represent_hour, "Heure représentation", class: "form-label" %>
  <%= form.text_field :represent_hour, class: "form-input" %>
  <%= form.label :represent_end_date, class: "form-label" %>
  <%= form.text_field :represent_end_date, class: "form-input" %>
  <%= form.label :represent_end_hour, class: "form-label" %>
  <%= form.text_field :represent_end_hour, class: "form-input" %>
  <%= form.label :price, "Prix", class: "form-label" %>
  <%= form.text_field :price, class: "form-input" %>
  <%= form.label :product_type, "Type de produit", class: "form-label" %>
  <%= form.text_field :product_type, class: "form-input" %>
  <%= form.label :sales_channel, "Filière de vente", class: "form-label" %>
  <%= form.text_field :sales_channel, class: "form-input" %>
  <%= form.label :lastname, "Nom", class: "form-label" %>
  <%= form.text_field :lastname, class: "form-input" %>
  <%= form.label :firstname, "Prenom", class: "form-label" %>
  <%= form.text_field :firstname, class: "form-input" %>
  <%= form.label :email, class: "form-label" %>
  <%= form.text_field :email, class: "form-input" %>
  <%= form.label :adress, "Adresse", class: "form-label" %>
  <%= form.text_field :adress, class: "form-input" %>
  <%= form.label :pcode, "Code postal", class: "form-label" %>
  <%= form.text_field :pcode, class: "form-input" %>
  <%= form.label :country, "Pays", class: "form-label" %>
  <%= form.text_field :country, class: "form-input" %>
  <%= form.label :age, class: "form-label" %>
  <%= form.text_field :age, class: "form-input" %>
  <%= form.label :gender, "Genre", class: "form-label" %>
  <%= form.text_field :gender, class: "form-input" %>
  <%= form.submit "Importer", class: "btn btn-primary input-group-btn my-2" %>
<% end %>

app/views/reservations/_results.html.erb
<div>Nombre de réservations : <%= @reservations.count %></div>
<div>Nombre d'acheteurs uniques : <%= @reservations.distinct.count(:email) %></div>
<div>
  Age moyen des acheteurs :
  <% if @reservations.average(:age).nil? %>
    Non spécifié.
  <% else %>
    <%= "#{@reservations.average(:age).floor} ans" %>
  <% end %>
</div>

app/views/reservations/custom.turbo_stream.erb
<%= turbo_stream.update "import", partial: "custom", locals: { reservation: @reservation } %>
<%= turbo_stream.replace "choisir" do %>
  <div class="my-2"><%= link_to "Revenir", new_reservation_path %></div>
<% end %>
<%= turbo_stream.remove "alert" %>

app/views/reservations/index.html.erb
<div class="column col-6 col-xl-8 col-lg-10 col-md-10 col-sm-12 col-xs-12 p-centered text-center">
  <%= link_to "Importer CSV", new_reservation_path, class: "btn btn-lg" %>
  <h1>Récapitulatif des données</h1>
  <div id="total">
    <h4>Total: </h4>
    <div>Nombre de réservations : <%= @reservations&.count %></div>
    <div>Nombre d'acheteurs uniques : <%= @reservations.distinct&.count(:email) %></div>
    <div>
      Age moyen des acheteurs :
      <% if @reservations.average(:age).nil? %>
        Non spécifié.
      <% else %>
        <%= "#{@reservations.average(:age).floor} ans" %>
      <% end %>
    </div>
  </div>

  <h4><%= link_to "Rechercher pour un spectacle", new_search_path, "data-turbo-frame": "new_search" %></h4>
  <%= turbo_frame_tag "new_search" %>
  <div id="results"></div>
  <div class="divider"></div>
  <h2>Prix moyen par représentation: </h2>
  <% if @reservations.any? %>
    <% @reservations.group(:represent).average(:price).each do |k, v| %>
      <div class="m-1"><span class="label label-primary"><%= k %> :</span> <%= "#{v.to_f.round(2)} €" %></div>
    <% end %>
  <% else %>
    <div>Aucune donnée fournie.</div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="column col-6 col-xl-8 col-lg-10 col-md-10 col-sm-12 col-xs-12 p-centered">
  <h1>Importer vos Réservations</h1>
  <%= form_with url: reservations_path, id: "import" do |form| %>
    <div class="input-group">
      <span class="input-group-addon">Importer CSV</span>
      <%= form.file_field :file, accept: ".csv", class: "form-input" %>
      <%= form.submit "Importer", class: "btn btn-primary input-group-btn" %>
    </div>
  <% end %>
  <div class="my-2"><%= link_to "Visualisation des données", reservations_path %></div>
  <div><%= link_to "Choisir nom des colonnes", custom_path, "data-turbo-stream": "", id: "choisir" %></div>
  <div id="custo"></div>
</div>

app/views/reservations/new_search.html.erb
<%= turbo_frame_tag "new_search" do %>
  <%= form_with url: "/search", method: :get, html: { "data-turbo-stream": "", "data-turbo-frame": "_top" } do |form| %>
    <div class="input-group">
      <%= form.text_field :query, placeholder: "Nom de Spectacle", class: "form-input" %>
      <%= form.submit "Rechercher", class: "btn btn-primary input-group-btn" %>
    </div>
  <% end %>
<% end %>

app/views/reservations/search.html.erb
<div>Nombre de réservations : <%= @reservations.count %></div>
<div>Nombre d'acheteurs uniques : <%= @reservations.distinct.count(:email) %></div>
<div>
  Age moyen des acheteurs :
  <% if @reservations.average(:age).nil? %>
    Non spécifié.
  <% else %>
    <%= "#{@reservations.average(:age).floor} ans" %>
  <% end %>
</div>

app/views/reservations/search.turbo_stream.erb
<%= turbo_stream.update "results", partial: "results", locals: { reservations: @reservations } %>
<%= turbo_stream.remove "notice" %>